# Generated by Django 3.0 on 2022-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(null=True, upload_to='main'),
        ),
    ]
